import { Flight } from "../models/types";

export const hardcodedFlights: Flight[] = [
    {
      number: 'TK 0001',
      airlines: 'Turkish Airlines',
      departureDate: '18 Apr 2024',
      arrivalDate: '19 Apr 2024',
      departure: 'New York',
      arrival: 'Los Angeles',
      departureTime: '08:00 AM',
      arrivalTime: '11:00 AM',
      duration: '9h 50m',
    },
    {
      number: 'TK 0001',
      airlines: 'Turkish Airlines',
      departureDate: '18 Apr 2024',
      arrivalDate: '19 Apr 2024',
      departure: 'Chicago',
      arrival: 'Miami',
      departureTime: '09:00 AM',
      arrivalTime: '12:00 PM',
      duration: '9h 50m',
    },
    {
      number: 'TK 0001',
      airlines: 'Turkish Airlines',
      departureDate: '18 Apr 2024',
      arrivalDate: '19 Apr 2024',
      departure: 'Izmir',
      arrival: 'Seattle',
      departureTime: '10:00 AM',
      arrivalTime: '01:00 PM',
      duration: '9h 50m',
    },
    {
      number: 'TK 0001',
      airlines: 'Turkish Airlines',
      departureDate: '18 Apr 2024',
      arrivalDate: '19 Apr 2024',
      departure: 'İstanbul',
      arrival: 'Tokyo',
      departureTime: '09:00 AM',
      arrivalTime: '12:00 PM',
      duration: '9h 50m',
    },
    {
      number: 'TK 0001',
      airlines: 'Turkish Airlines',
      departureDate: '18 Apr 2024',
      arrivalDate: '19 Apr 2024',
      departure: 'London',
      arrival: 'Paris',
      departureTime: '09:00 AM',
      arrivalTime: '12:00 PM',
      duration: '9h 50m',
    },
    {
      number: 'TK 0001',
      airlines: 'Turkish Airlines',
      departureDate: '18 Apr 2024',
      arrivalDate: '19 Apr 2024',
      departure: 'Osaka',
      arrival: 'Izmir',
      departureTime: '09:00 AM',
      arrivalTime: '12:00 PM',
      duration: '9h 50m',
    },
    {
      number: 'TK 0001',
      airlines: 'Turkish Airlines',
      departureDate: '18 Apr 2024',
      arrivalDate: '19 Apr 2024',
      departure: 'Ankara',
      arrival: 'Rotterdam',
      departureTime: '08:00 AM',
      arrivalTime: '16:00 PM',
      duration: '9h 50m',
    },
    {
      number: 'TK 0001',
      airlines: 'Turkish Airlines',
      departureDate: '18 Apr 2024',
      arrivalDate: '19 Apr 2024',
      departure: 'Samsun',
      arrival: 'Ankara',
      departureTime: '08:00 AM',
      arrivalTime: '16:00 PM',
      duration: '9h 50m',
    },
    {
      number: 'TK 0001',
      airlines: 'Turkish Airlines',
      departureDate: '18 Apr 2024',
      arrivalDate: '19 Apr 2024',
      departure: 'Konya',
      arrival: 'Antalya',
      departureTime: '08:00 AM',
      arrivalTime: '16:00 PM',
      duration: '9h 50m',
    },
  ];